### ISSUE TITLE
Is it possible to customize inner css class?

### ISSUE THREAD

**Issue by gwd0715** [arnau/obsidian-metatable#14]
Other than .obsidian-metatable class, can we customize other css class like .set or .member?
I tried to change them in CSS snippets, but failed!
Thanks!

**Comment by arnau** [comment]
Hi @gwd0715, the short answer is no, by design the whole component is constrained under a shadow DOM which acts as a hard boundary for CSS so CSS from the outside doesn't conflict with the inside and vice-versa.

For certain parts there are hooks via `::part` (e.g. [tags](https://github.com/arnau/obsidian-metatable#tags)) but the possibilities for customisation are quite limited.
