### ISSUE TITLE
Inconsistent tag behavior

### ISSUE THREAD

**Issue by alanalvarado** [arnau/obsidian-metatable#26]
Hello! nice work there!

The problem : I have md files created by a lot of different means, (different browser clippers, copied markdown, clear-mark, manually created) so the frontmatter syntax/keywords are not uniform i.e especially with tags. and each syntax gives different result.

---
tags: osx docs bash
---
Result: only one clickable tag called "osx docs bash"

---
Tags: osx docs bash
---
Result: not clickable tags

---
tags: [osx, docs, bash]
---
Result: each tag separated, working correctly (this is the expected result with any syntax capitalization combination)

---
Tags: [osx, docs, bash]
---
Result: Bullet List with no clickable items. 

Thanks in advance.

**Comment by arnau** [comment]
Hi @alanalvarado, thanks for reporting. I see that in both situations Obsidian defaults to your expected behaviour.

For the capitalised `Tags` vs lowercsae `tags` I see little risk and will treat it as a bug.

For the string `osx docs bash` vs array `[osx, docs, bash]` let me think about it. It diverges from standard YAML which I don't particularly favour.

**Comment by arnau** [comment]
On reflection, I think both features should be implemented. The value of `tags` is already non-standard because `a, b, c` is treated as an array.
