### ISSUE TITLE
[Bug] Issue with folding front matter in preview

### ISSUE THREAD

**Issue by Archie-2021** [arnau/obsidian-metatable#35]
When i fold front matter and switch to reading mode  and coming back to live-preview it forgets the folding. This only happens when your plugin be active.

**Comment by arnau** [comment]
Hi, I'm not entirely sure I'm following. Let me replay what I understood:

1. Open file in reaading mode
2. fold the Metatable block
3. switch to editing mode (defaults to live preview)
4. NOTE: live preview shows the raw YAML because the Metatable plugin cannot be rendered in this view
5. switch back to reading mode

If I follow the steps above the folding persists. However, if I close the file and open it again it does not persist. If this is the problem you observe, it's not a bug, it's a limitation.

**Comment by Archie-2021** [comment]
> Hi, I'm not entirely sure I'm following. Let me replay what I understood:
> 
> 1. Open file in reaading mode
> 2. fold the Metatable block
> 3. switch to editing mode (defaults to live preview)
> 4. NOTE: live preview shows the raw YAML because the Metatable plugin cannot be rendered in this view
> 5. switch back to reading mode
> 
> If I follow the steps above the folding persists. However, if I close the file and open it again it does not persist. If this is the problem you observe, it's not a bug, it's a limitation.

to explain more:
1. open a note in edit/live-preview mode
2. fold the front yaml using fold under the cursor Obsidian command
3.change the view to reading mode
4. change back the view to edit/live-preview mode

and the folding is gone and yaml is open. it is not the issue of even leaving the note. it is not remembered at all if view being changed.

**Comment by arnau** [comment]
Ah! understood. And I can reproduce the behaviour 👍 

I'll have to dig into this one, thanks for reporting.

**Comment by arnau** [comment]
The new version 0.12.0 should fix this issue.
